repos:
-   repo: local
    hooks:
    -   id: fourmolu
        name: fourmolu
        description: "Formatter for Haskell source code."
        entry: fourmolu -i modulus-ai-be
        language: system
        types: [haskell]
