name:                ai-chatbot-hs
version:             0.1.0.0
github:              "tusharad/ai-chatbot-hs"
license:             MIT
author:              "tushar"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2025 tushar"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A AI chatbot clone
category:            Web

description:         Please see the README on GitHub at <https://github.com/tusharad/ai-chatbot-hs#readme>

dependencies:
- base >= 4.7 && < 5
- hyperbole
- text
- aeson
- bytestring
- wai-middleware-static
- atomic-css
- containers
- effectful-core
- network-uri
- sqlite-simple
- langchain-hs
- wai
- http-types
- scotty
- ollama-haskell >= 0.2
- uuid
- megaparsec
- time
- transformers
- wai-extra
- string-interpolate

default-extensions:
 - DataKinds 
 - DeriveAnyClass 
 - DeriveGeneric 
 - FlexibleContexts 
 - FlexibleInstances 
 - LambdaCase 
 - MultiParamTypeClasses 
 - NamedFieldPuns 
 - OverloadedStrings 
 - RecordWildCards 
 - StandaloneDeriving 
 - TypeApplications 
 - TypeFamilies 
 - TypeOperators 
 - UndecidableInstances 

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ai-chatbot-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ai-chatbot-hs

tests:
  ai-chatbot-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ai-chatbot-hs
