name: modulus-ai
version: 0.0.1.0
github: "tusharad/modulus-ai"
license: MIT
author: "tushar"
maintainer: "tusharadhatrao@gmail.com"
copyright: "2025 tushar"

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis: An AI chatbot that lets you interact with LLMs from different providers.
category: Web
description: Please see the README on GitHub at <https://github.com/tusharad/modulus-ai#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - atomic-css
  - bytestring
  - containers
  - effectful-core
  - email-validate
  - fast-logger
  - http-client
  - http-client-tls
  - http-types
  - hyperbole
  - jose
  - lens
  - mtl
  - network-uri
  - orville-postgresql
  - password
  - random
  - req
  - servant-server
  - servant-client
  - servant-client-core
  - string-interpolate
  - text
  - time
  - transformers
  - unliftio
  - uuid
  - wai
  - wai-extra
  - wai-middleware-static
  - warp

default-extensions:
 - DataKinds 
 - DeriveAnyClass 
 - DeriveGeneric 
 - FlexibleContexts 
 - FlexibleInstances 
 - LambdaCase 
 - MultiParamTypeClasses 
 - NamedFieldPuns 
 - OverloadedStrings 
 - RecordWildCards 
 - StandaloneDeriving 
 - TypeApplications 
 - TypeFamilies 
 - TypeOperators 
 - UndecidableInstances 

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  modulus-ai-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - modulus-ai

tests:
  modulus-ai-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - modulus-ai
      - tasty
      - tasty-hunit
