FROM debian:trixie-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libgmp10 \
    zlib1g \
    libpq5 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd -r appuser && useradd -r -g appuser -m appuser
USER appuser

WORKDIR /home/appuser/app

COPY --chown=appuser:appuser modulus-ai-exe .
COPY --chown=appuser:appuser public ./public

CMD ["./modulus-ai-exe"]
