name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-fourmolu@v11
        with:
          version: "latest"

  hlint:
    needs: format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.10'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: modulus-ai-be/src/
        fail-on: warning

  build_test_package:
    needs: hlint
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./modulus-ai-be/
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5
      with:
        working-directory: ./modulus-ai-be/
        stack-build-arguments: --copy-bins

    - name: Copy binary for docker
      run: cp /home/runner/.local/bin/modulus-ai-exe ./modulus-ai-exe
    
    - name: Build docker image
      run: |
          docker build -f dockerfile.release -t modulus-ai:release .

    - name: Save docker image to tarball
      run: |
          docker save modulus-ai:release -o modulus-ai-image.tar
          ls -lh modulus-ai-image.tar

    - name: Upload image artifact (1 day retention)
      uses: actions/upload-artifact@v4
      with:
          name: modulus-ai-image
          path: modulus-ai-be/modulus-ai-image.tar
          retention-days: 1
