name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: haskread
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/haskread/modulus-ai-repo

permissions:
  contents: read

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-fourmolu@v11
        with:
          version: "latest"

  hlint:
    needs: format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Set up HLint'
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.10'

    - name: 'Run HLint'
      uses: haskell-actions/hlint-run@v2
      with:
        path: modulus-ai-be/src/
        fail-on: warning

  test:
    needs: hlint
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./modulus-ai-be/
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5
      with:
        working-directory: ./modulus-ai-be/

  push_backend_image:
    needs: test
    runs-on: ubuntu-22.04
    environment: development
    defaults:
      run:
        working-directory: ./modulus-ai-be/
        shell: bash

    steps:
    - name: Copy repo into actions 
      uses: actions/checkout@v4

    - name: install dependancies, build and test stack project.
      uses: freckle/stack-action@v5
      with:
        working-directory: ./modulus-ai-be/
        stack-build-arguments: --copy-bins

    - name: Copy binary for docker
      run: cp /home/runner/.local/bin/modulus-ai-exe ./modulus-ai-exe

    - id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"

    - name: "Docker auth"
      run: |-
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build docker image
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        IMAGE_NAME=${{ env.GAR_LOCATION }}/modulus-ai-backend:$COMMIT_HASH
        docker build -f dockerfile.release -t $IMAGE_NAME .

    - name: Push image
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        IMAGE_NAME=${{ env.GAR_LOCATION }}/modulus-ai-backend:$COMMIT_HASH
        docker push $IMAGE_NAME

  frontend:
    runs-on: ubuntu-22.04
    environment: development
    defaults:
      run:
        working-directory: ./modulus-ai-fe/
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build docker image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          IMAGE_NAME=${{ env.GAR_LOCATION }}/modulus-ai-frontend:COMMIT_HASH
          docker build -f dockerfile.release -t $IMAGE_NAME .

      - name: Push image
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          IMAGE_NAME=${{ env.GAR_LOCATION }}/modulus-ai-frontend:COMMIT_HASH
          docker push $IMAGE_NAME
